plent/config/routes.rb
Rails.application.routes.draw do

  get 'my_pages/new'
  get 'my_pages/edit'
  get 'my_pages/index'
  post 'my_pages/new' => 'my_pages/new', defaults: {format: 'js'}
  #로그인관련
  devise_for :users
  # 
  get 'events/main'
  get 'events/index'
  get 'events/new'
  get 'events/show'
  post 'events/index' => 'events#index', defaults: {format: 'js'}
  post 'events/show' => 'events#show', defaults: {format: 'js'}
  post 'events/search' => 'events#search', defaults: {format: 'js'}

  root 'events#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_pages do
	resources :comments 
end

end

plent/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

plent/app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :tags
  mount_uploader :image, ImageUploader

end

plent/app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :events
end

plent/app/models/user.rb
class User < ApplicationRecord

  has_and_belongs_to_many :events	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

plent/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

plent/app/controllers/events_controller.rb
  class EventsController < ApplicationController

    #일단 액션 세팅 

    #before_action :authenticate_user!, except: [:main, :index]
    def main #메인페이지
      @tags1 = Tag.where(category: '유형')
      @tags2 = Tag.where(category: '주제')
      @events = Event.all

      #@this_month = Time.now.month
      t = Time.now
      #이번달 범위 설정. 함수를 모델에 넣어 두는게 좋을까? 
      @month_range = t.beginning_of_month..t.end_of_month
      @month_events = Event.where(:date => @month_range)
      
    end

    def index #검색된 페이지. 태그에 맞는것들만 불러오기
      @tags = Tag.all

    ## Main에서 넘어온 애들 처리 + Index에서 태그 검색      
      @s = Array.new
    # strong params만 추가하면 된다!!
      if params[:id] == nil
    # 밑에 like 구문은 안전하지 못함. 나중에 스트롱하게 바꾸자
        if params[:event] 
          @s = Event.where("title LIKE '%#{params[:event]}%' OR title LIKE '%#{params[:event]}%'")
        else
          @s = Event.all
        end
      else
        params[:id].each do |f|
          if params[:event]    
            Tag.find_by_id(f).events.where("title LIKE '%#{params[:event]}%' OR title LIKE '%#{params[:event]}%'").each do |d|
            @s.push(d)
            end
          else
           Tag.find_by_id(f).events.each do |d|
             @s.push(d)
            end
          end
        end
      end

      if request.post?
        respond_to do |format|
        format.js { render partial: 'results'}
         end
      end
    end


    def show # 상세페이지
      @event = Event.find(params[:id])
      @tag = Tag.find(@event.tags.ids)
      respond_to do |format|
      format.js { render 'show' }
    
    end
      #@events = Array.new
      #if params[:id]

    #    @events.push(Event.find(params[:id]))
      #@events.push(@event)
    #elsif params[:ids]
     # params[:ids].each do |q|
      #  @events.push(Event.find(q))
     # end
    #end
    #respond_to do |format|
     # format.js { render 'show' }
    #end
  end

    def new # 게시물 올리는 페이지
      @event = Event.new # db 안넣은 빈 모델
      @year = Time.now.year
      @tags = Tag.all
    end

    def edit # 올린 사람이 편집하는 페이지
      @event = Event.find(params[:id])
    end

    def update # edit 액션의 post request
      @event = Event.find(params[:id])

      if @event.update(events_params)
        redirect_to action: "index"
      else
        render 'edit'
      end
      
    end
    def create # new 액션의 post request
      @event = Event.new(event_params)
      if @event.save #model validation 통과해서 만들어치면 true
        #redirect_to @event #my_post로 가도록 재설정해야
        redirect_to action: "index"
      else
        render 'new'  
      end
    end

    def destroy # 삭제 request . 관리자만의 기능으로 해야할듯
      @event = Event.find(params[:id])
      @event.destroy
    end

    private # Strong Params (보안)
    def events_params
     params.require(:event).permit!
   end

      #선택된 Tag id로 Tag db 찾는 함수. 아직 실패한 함수
      def selected_tags
        params[:tag].each do |t|
         @t = Tag.find_by(:id => "#{t}")
       end

     end

   end

plent/app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  

  def index
  	@user_events = User.first.events
  end

  def new # 게시물 올리는 페이지
  	@event = Event.new # db 안넣은 빈 모델
  	@year = Time.now.year
  	@tags = Tag.all


  	if request.post?
        respond_to do |format|
        format.js { render 'new'}
         end
      end

  end

  def edit # 올린 사람이 편집하는 페이지
  	@event = Event.find(params[:id])
  end

  def update # edit 액션의 post request
  	@event = Event.find(params[:id])
 
  if @event.update(event_params)
    redirect_to action: "index"
  else
    render 'edit'
  end
  	
  end

  def create # new 액션의 post request
  	@event = Event.new(event_params)

     
      #if tag_params
      #  tag_params.each do|w|
      if params['event']['id']
      params['event']['id'].each do |w|
        @event.tags << Tag.find_by_id(w)
      end
      end	
    
  	if @event.save #model validation 통과해서 만들어치면 true
  		#redirect_to @event #my_post로 가도록 재설정해야
  		redirect_to action: "index"
  	else
  		render 'new'	
  	end

  	
  end

  def destroy # 삭제 request . 올린사람만 할수있게 해야할듯
  	@event = Event.find(params[:id])
  	@event.destroy
  end

  private # Strong Params (보안) 함수가 원라인이면 return 생략 가능한 루비
  def event_params # 아직 이미지 열은 안만들었음
  	params.require(:event).permit!
  end

  def tag_params #strong
  	params.require(:event).permit({ id: [] })
  	
  end

end

plent/app/helpers/application_helper.rb
module ApplicationHelper
end

plent/app/helpers/events_helper.rb
module EventsHelper
end

plent/app/helpers/my_pages_helper.rb
module MyPagesHelper
end

plent/app/views/events/_results.js.erb
$("#before_search").hide();
$("#search_results").html("<%= escape_javascript(render :partial => 'search_results') %>");

plent/app/views/events/_search_results.html.erb
<% @s.each do |a|%>
<div class = "event_card">
<p><% if a.image%>
	<%= image_tag a.image.card.url %>
	<% end %></p>
<!-- 위에가 사진 / 밑에가 행사 제목 -->
<p><%= link_to "#{a.title}", events_show_path(:id => a.id), remote: true, method: "post"%></p>
</div>
<% end %>

plent/app/views/events/_show.html.erb
<% if @event %>

<section id="eventdetail">
  <!--전체 상세 페이지 영역입니다-->
  <!--행사 이름을 보여주는 영역입니다-->
  <div class="event-name">


    <% e = @event %>
    <p><%= e.title%></p>
  </div>
  <!--행사 정보를 보여주는 영역입니다-->
  <div class="event-info">
    <ul class=eventinfo><div class="event-info_firstitem">
      <li class = "col-1"> 일시 <%= e.date %></li>
      <li class = "col-1"> 장소 <%= e.location %></li>
      <li class = "col-1"> 분류 <%@tag.each do|t|%><%=t.name%> <%end%></li></ul>
    </div>
    <div class="event-info_seconditem">
      <span class="col-1">  본문 <%= e.text %></span>
    </div>

    <!--poster를 보여주는 영역입니다.-->
    <div class="show_poster">
      <%=image_tag e.image.url %>
      <div class="show-poster_wrapper">
      </div></div>



      <aside id="side-button">
        <!--<%= submit_tag("search", :class=>"search-button")%>-->

        <button class="like">like</button>
        <!--<button class="kakaotalk">kakao</button>-->
      </aside>

    </section>
    <% end %>

plent/app/views/events/_tag_box.html.erb
<div class = "tag_box">	
		<ul>		
			<% @tags.each do |t| %>
			<li><%= f.check_box :id, {:id => "#{t}", :class =>"index_tag", multiple: true}, "#{t.id}", nil %>
				<%= f.label :id, "#{t.name}", :for => "#{t}" %></li>
				<% end %>
			<li>x이미지</li>
		</ul>
	</div>

plent/app/views/events/index.html.erb
<section class = index_left>
	<%= form_with( url: events_index_path, method: "post", class: "main_tags_form", class: "hahaha") do |f| %>
	<div id="index-search">

		<%= submit_tag("행사찾기", :class=>"search-button")%>
		<%= f.search_field :event, id: 'insearch_field' %>

	</div>
	<div>
		<!-- _tag_box.html.erb 불러오기 -->
		<%= render 'tag_box', f: f %>
	</div>
	<% end %>

	<div id = "before_search">
		<%= render 'search_results' %>
	</div>
	<div id = "search_results">
	</div>
</section>

<aside class = index_right>
	<div id = "show">
	</div>
</aside>

plent/app/views/events/main.html.erb
<div class = "wrapper">
	<div id = "blue" class = "section">
		<div class = "bluemargin">

			<section class = "forme_event">
				<p>나를 위한<br>교내 행사<br>직접 찾아보기</p>
				<%= image_tag "bluearrow.png", :class => "bluearrow" %>
			</section>

			<aside class = "main_tags_search">

				<!-- form_with는 local: true 안해주면 ajax 방식(remote: true)임!!-->
				<%= form_with(url: events_index_path, method: "get", local: true) do |f| %>
				
				<% @tags1.each do |t| %>
				<ul class ="tag1">
					<li><%= f.check_box :id, {:id => "#{t}", :class =>"main_tag",multiple: true}, "#{t.id}", nil %>
						<%= f.label :id, "#{t.name}", :for => "#{t}" %></li>
					</ul>
					<% end %>

					<% @tags2.each do |t| %>
					<ul class ="tag2">

						<li><%= f.check_box :id, {:id => "#{t}", :class =>"main_tag",multiple: true}, "#{t.id}", nil %>
							<%= f.label :id, "#{t.name}", :for => "#{t}" %></li>
						</ul>
						<% end %>

					</aside>

					<ul class = "main_search">
						<li><%= f.search_field :event %>
							<%= submit_tag("Search", :class =>"submit_button") %> </li>
						</ul>

						<% end %>
					</div>
				</div>

				<div id = "mint" class = "section">

					<section class = "month_event">
						<p>이달의 행사</p> 
						<%= image_tag "mintarrow.png", :class => "mintarrow" %>
					</section>

					<aside class = "mint_calender">
						<%= month_calendar do |dat| %>
						
						<!-- 툴팁 css가 적용 안되는 문제. simple calendar 때문인듯...-->

						<% a = Array.new %>
						<% @month_events.each do |m| %>
						<% if m.date.day == dat.day %>
						<% a.push(m) %>
						<% end %>
						<% end %>

						<button class="myBtn"><%= link_to "#{dat.day}", events_show_path(:ids => a.map(&:id)), remote: true, method: "post"%></button> 

						<% end %>
					</aside>
					<!-- Trigger/Open The Modal -->
					<!-- 날짜누르면  모달 뜸 -->
					<div id="myModal" class="modal">

						<!-- Modal content -->
						<div class="modal-content">
							<span class="close">&times;</span>
							<div id = "show"></div>								
						</div>
					</div>
				</div>

				<div id = "red" class = "section">
					<div class = "bluemargin">
						<section class = "month_event">
							<p>더 알아보기</p>
							<%= image_tag "mintarrow.png", :class => "redarrow" %>
						</section>
						<aside class = "red_about">
							<p> PLENT는 관심있는 교내 행사를 골라 한눈에 모아볼 수 있는 검색 웹 서비스입니다. 2019년도 웹프로그래밍 과제로 금진섭, 박나윤, 조가영이 만들었습니다.</p>
						</aside>
					</div>
				</div>
			</div>

			<!-- 메인 풀페이지 설정-->
  <script type="text/javascript">
      $(document).ready(function(){
        $('.wrapper').fullpage();
        $('.wrapper1').fullpage();
      });
    </script>

plent/app/views/events/modal.js.erb
$("#modal_show").html("<%= escape_javascript(render :partial => 'show') %>");

plent/app/views/events/my_page.html.erb
<h1>Events#my_page</h1>
<p>Find me in app/views/events/my_page.html.erb</p>

plent/app/views/events/show.js.erb
$("#show").html("<%= escape_javascript(render :partial => 'show') %>");

plent/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8"> <!--이거 세팅해야되나? rails의 default를 잘 모르겠다 -->
    <!-- 모바일에서도 적용되려면 아래 세팅 해야된다고 하길래 일단 넣어봄. 필요없으면 빼자-->
<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" /> -->


    <title>PLENT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
   
  </head>

  <body>
    <!--여기에 header랑 footer 공통으로 넣자. 모든 controller에 공통하게 들어갈 것이기 때문에. 그렇지 않다면 각 view 폴더에 _form으로 넣는게 좋다 -->
    <header>      
        <a class = "logo" href ="../events/main" target="_self">PLENT</a>
        <nav class = "menu">     
        <ul>
          <li>ABOUT</li>
          <li><%= link_to 'LOGIN', new_user_session_path %></li>
          <li><%= link_to 'MY PAGE', my_pages_index_path %> </li>
        </ul>
        </nav>              
    </header>
    
    <div class = "each_html">
    <%= yield %>
    </div>
  
  
  </body>
</html>

plent/app/views/my_pages/_new.html.erb
<div class = "my_page_new">

	<%= form_with model: @event, scope: :event, url: my_pages_path, local: true do |f| %>

	<div class = "create_form_left">
		<p>
			<%= f.label :제목, :class => "label_name" %>
			<%= f.text_field :title, :class => "title_field" %>
		</p>
		<p>
			<%= f.label :일시, :class => "label_name" %>
			<%= f.datetime_select :date, start_year: @year, ampm: true, prompt: {month: '월', day: '일', hour: '시간' }, :class => "datetime_select" %>
		</p>
		<p>
			<%= f.label :이미지, :class => "label_name" %>
			<!-- edit 페이지에서 사용할 미리보기 -->
			<%= image_tag(@event.image_url) if @event.image? %>
			<%= f.file_field :image, :class => "image_field" , :onchange => "previewFile();"%>
			<!-- 이미지 프리뷰 -->
			<img src="" height="200">
			<%= f.hidden_field :image_cache %>

		</p>

		<p>
			<%= f.label :장소, :class => "label_name" %>
			<%= f.text_field :location, :class => "location_field" %>
		</p>
		<p>
			<%= f.label :본문, :class => "label_name" %>
			<%= f.text_area :text, :class => "text_field" %>
		</p>

		<p>
			
			<%= f.label :태그, :class => "label_name" %>
			<%= f.fields_for :tags, @event.tags.build do |q|%>
			<div class= "tag_field">
				<%= render 'events/tag_box', q: q  %>
					
			</div>
			<% end %>
		</p>
	</div>

		<div class = "create_form_right">
		<p>
		  <%= f.submit("행사찾기", :class =>"submit") %>
		</p>
	</div>

	<% end %>

</div>

<script>
function previewFile() {
  var preview = document.querySelector('img');
  var file    = document.querySelector('input[type=file]').files[0];
  var reader  = new FileReader();

  reader.addEventListener("load", function () {
    preview.src = reader.result;
  }, false);

  if (file) {
    reader.readAsDataURL(file);
  }
}
</script>

plent/app/views/my_pages/_tag_box.html.erb
<div class = "tag_box">	
		<ul>		
			<% @tags.each do |t| %>
			<li><%= check_box :tag, {:id => "#{t}", :class =>"index_tag", multiple: true}, "#{t.id}", nil %>
				<%= label :tag, "#{t.name}", :for => "#{t}" %></li>
				<% end %>
			<li>x이미지</li>
		</ul>
	</div>

plent/app/views/my_pages/edit.html.erb
<h1>MyPages#edit</h1>
<p>Find me in app/views/my_pages/edit.html.erb</p>

plent/app/views/my_pages/index.html.erb
<div class = "buttons">
	<ul>	
		<li><%= button_to "내가 찜한 행사", action: "new" %></li>
		<li><%= button_to "행사 등록하기", action: "new", remote: true, method: "post" %></li>
		<li><%= button_to "등록한 행사", action: "new" %></li>
		<li><%= button_to "내 정보 관리", action: "new" %></li>
	</ul>
</div>


<div>
	

</div>

<section id = "like_list">
	<% @user_events.each do |e|%>
	<div class="my_pages_container">
		<!-- list를 보여주는 공간입니다-->
		<div class="list-container" style = "margin-top: 0">
			<div class="list-leftitem">
				<div class="list1">
					<p><%= e.title %></p>
					<input type="checkbox" id="mark_my_pages">
				</div>
				<div class="list2">
					<p id="date"><%= e.date %></p>
					<p></p>
				</div>
				<div class="list3">
					<p><%= e.text%></p>
					
				</div>
				<div class="list4">
					<p class="marginright"></p>
					<p></p>
				</div>
			</div>
			<div class="list-rightitem">
				<div class="list-poster" style="max-height: 100%">
					<%= image_tag e.image.card.url %>
				</div>
			</div>
		</div>
		<% end %>
	</section> 
	<section id = "new_event"></section>                                               

plent/app/views/my_pages/new.html.erb
<div class = "my_page_new">

	<%= form_with model: @event, scope: :event, url: my_pages_path, local: true do |f| %>

	<div class = "create_form_left">
		<p>
			<%= f.label :제목, :class => "label_name" %>
			<%= f.text_field :title, :class => "title_field" %>
		</p>
		<p>
			<%= f.label :일시, :class => "label_name" %>
			<%= f.datetime_select :date, start_year: @year, ampm: true, prompt: {month: '월', day: '일', hour: '시간' }, :class => "datetime_select" %>
		</p>
		<p>
			<%= f.label :이미지, :class => "label_name" %>
			<!-- edit 페이지에서 사용할 미리보기 -->
			<%= image_tag(@event.image_url) if @event.image? %>
			<%= f.file_field :image, :class => "image_field" , :onchange => "previewFile();"%>
			<!-- 이미지 프리뷰 -->
			<img src="" height="200">
			<%= f.hidden_field :image_cache %>

		</p>

		<p>
			<%= f.label :장소, :class => "label_name" %>
			<%= f.text_field :location, :class => "location_field" %>
		</p>
		<p>
			<%= f.label :본문, :class => "label_name" %>
			<%= f.text_area :text, :class => "text_field" %>
		</p>

		<p>
			
			<%= f.label :태그, :class => "label_name" %>
			
			<div class= "tag_field">
				<%= render 'events/tag_box', f: f  %>
					
			</div>
			
		</p>
	</div>

		<div class = "create_form_right">
		<p>
		  <%= f.submit("행사찾기", :class =>"submit") %>
		</p>
	</div>

	<% end %>

</div>

<script>
function previewFile() {
  var preview = document.querySelector('img');
  var file    = document.querySelector('input[type=file]').files[0];
  var reader  = new FileReader();

  reader.addEventListener("load", function () {
    preview.src = reader.result;
  }, false);

  if (file) {
    reader.readAsDataURL(file);
  }
}
</script>

plent/app/views/my_pages/new.js.erb
$("#like_list").hide();
$("#new_event").html("<%= escape_javascript(render :partial => 'new') %>");